apiVersion: apps/v1
kind: Deployment
metadata:
  name: huma-rest-example-deployment
  labels:
    app: huma-rest-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: huma-rest-example
  template:
    metadata:
      labels:
        app: huma-rest-example
    spec:
      containers:
      - name: huma-rest-example
        image: huma-rest-example:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: huma-rest-example-config
              key: SERVICE_PORT
        - name: SERVICE_LOGGER_FORMAT
          valueFrom:
            configMapKeyRef:
              name: huma-rest-example-config
              key: SERVICE_LOGGER_FORMAT
        livenessProbe:
          httpGet:
            port: http
            path: /liveness
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: http
            path: /readiness
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: huma-rest-example-service
spec:
  selector:
    app: huma-rest-example
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
