name: go-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test
      run: go test -v ./... -cover

    - name: Race
      run: go test -v ./... -race
